spring.application.name=bff-gateway
server.port=8080

smartlogix.inventario.url=http://localhost:8081
smartlogix.pedidos.url=http://localhost:8082
smartlogix.envios.url=http://localhost:8083

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
